SELECT HISTORY_ID, CAR_ID
     , DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE
     , DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
     
-- RENT_TYPE: 대여 기간이 30일 이상이면 '장기 대여' 그렇지 않으면 '단기 대여'
CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30
    THEN '장기 대여' 
    ELSE '단기 대여' 
    END RENT_TYPE

FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY

WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC;