SELECT WAREHOUSE_ID
     , WAREHOUSE_NAME
     , ADDRESS
    -- 냉동시설 여부가 NULL인 경우, 'N'
     , CASE WHEN FREEZER_YN IS NULL THEN 'N' ELSE FREEZER_YN END FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '경기도%'
ORDER BY WAREHOUSE_ID;