-- BOOK 테이블의 BOOK_ID와 PUBLISHED_DATE
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE FROM BOOK
WHERE PUBLISHED_DATE LIKE '2021-%' -- 2021년 출판
AND CATEGORY='인문' -- '인문' 카테고리
ORDER BY PUBLISHED_DATE ASC;    -- 출판일 기준으로 오름차순